### ISSUE TITLE
get the different ip each time?? 

### ISSUE THREAD

**Issue by mygoare** [ysmood/myip#1]
![image](https://user-images.githubusercontent.com/950850/57963595-cde60e80-7958-11e9-8cae-a46ab29c4fa3.png)

each time get the different ip?
among them get ipv4, but sometimes ipv6 ?

**Comment by ysmood** [comment]
My home server uses it as a key component of ddns every day, no issue at all for 3 months now, need more info to reproduce your issue. At least please show me your test code.

**Comment by mygoare** [comment]
misunderstand the usage of the repo...

**Comment by ysmood** [comment]
From the readme, you can find two methods and their explanation, maybe you want to use `GetInterfaceIP` other than `GetPublicIP`

**Comment by ysmood** [comment]
@mygoare From the readme, you can find two methods and their explanation, maybe you want to use `GetInterfaceIP` other than `GetPublicIP`
